 CREATE SEQUENCE  "CASE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
 
 

  CREATE TABLE "CVD_CASE_MASTER" 
   (	"CASE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"SOURCE" VARCHAR2(60) NOT NULL ENABLE, 
	"CASE_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(15) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(30), 
	"DATE_OF_BIRTH" DATE NOT NULL ENABLE, 
	"NATIONAL_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"NATIONAL_ID_TYPE" VARCHAR2(30) NOT NULL ENABLE, 
	"STREET_ADDRESS" VARCHAR2(50) NOT NULL ENABLE, 
	"CITY" VARCHAR2(30) NOT NULL ENABLE, 
	"STATE" VARCHAR2(30) NOT NULL ENABLE, 
	"POSTAL" VARCHAR2(30) NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(30) NOT NULL ENABLE, 
	"CREATE_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_DATE" DATE NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(30), 
	"UPDATE_BY" VARCHAR2(30), 
	 CONSTRAINT "CASE_ID_PK" PRIMARY KEY ("CASE_ID"));
 

CREATE OR REPLACE TRIGGER "CASE_ID_TR" 
    BEFORE INSERT ON "CVD_CASE_MASTER"
    FOR EACH ROW
BEGIN
  SELECT CASE_SEQ.NEXTVAL
  INTO   :new.CASE_ID
  FROM   dual;
END;


ALTER TRIGGER "CASE_ID_TR" ENABLE;

select * from CVD_CASE_MASTER;
