
  CREATE TABLE "SYSTEM"."CVD_CASE_MASTER" 
   (	"CASE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"SOURCE" VARCHAR2(60) NOT NULL ENABLE, 
	"CASE_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(15) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(30), 
	"DATE_OF_BIRTH" DATE NOT NULL ENABLE, 
	"NATIONAL_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"NATIONAL_ID_TYPE" VARCHAR2(30) NOT NULL ENABLE, 
	"STREET_ADDRESS" VARCHAR2(50) NOT NULL ENABLE, 
	"CITY" VARCHAR2(30) NOT NULL ENABLE, 
	"STATE" VARCHAR2(30) NOT NULL ENABLE, 
	"POSTAL" VARCHAR2(30) NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(30) NOT NULL ENABLE, 
	"CREATE_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_DATE" DATE NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(30), 
	"UPDATE_BY" VARCHAR2(30), 
	 CONSTRAINT "CASE_ID_PK" PRIMARY KEY ("CASE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" 
 

  CREATE OR REPLACE TRIGGER "SYSTEM"."CASE_BIR" 
BEFORE INSERT ON cvd_case_master 
FOR EACH ROW

BEGIN
  SELECT case_seq.NEXTVAL
  INTO   :new.case_id
  FROM   dual;
END;


ALTER TRIGGER "SYSTEM"."CASE_BIR" ENABLE